extend type Query {
    getAllSubcription:[Subcription] @all (model: "App\\Models\\Suscripcion")
    promotionValidity(requestPromotion:JSON):responseValidityPromotion @field (resolver: "SubcriptionQuery@validationDatePromotion")
    getDateExpiration:responsePromotion @field(resolver: "SubcriptionQuery@expirationPromotion")
    getPromotionFalse:responsePromotion @field(resolver: "SubcriptionQuery@falsePromotion")
    getPromotionValid:responsePromotion @field(resolver: "SubcriptionQuery@promotionValid")
    validationSuscriptionPromotion(requestSubcriptionPromotion:JSON):responseSuscription @field(resolver: "SubcriptionQuery@getSubcriptionPromotion")
}

type responseValidityPromotion{
    message:String
    promocion:Promotion
}

type responsePromotion {
    message:String
    promocion:[Promotion]
}

type responseSuscription {
    message:String
    result:Boolean
    technician:Technician
    suscripcion:Subcription
    promocion:Promotion
}
#import subcription.graphql
