extend type Query {
    reportSuscription(Input:requestReportSuscription):responseReportSuscription @field(resolver: "ReportQuery@reportSuscription")
    reportTechnician(Input:RequestReportTechnicians):responseReportTech @field(resolver: "ReportQuery@reportTechnician")
    reportClient(Input:requestReportClient):responseReportClient @field(resolver: "ReportQuery@reportClient")
}

input requestReportClient {
    cities:String
    activity:String
    status:Boolean
}

type responseReportClient {
    message:String
    content:[reportClient]
}

type reportClient {
    id_client:string
    full_name:String
    name_city:String
    countService:String
    status:String
}

input RequestReportTechnicians{
    skills:String
    cities:String
    rates:Int
    status:String
}

type responseReportTech {
    message:String
    techniciansData:[reportTechs]
}

type reportTechs{
    id:String
    name_technician:String
    name_city:String
    name_skills:String
    rates:String
    status:String
}

input requestReportSuscription {
    startDate:String
    endDate:String
    type:String
    state:String
    status:Boolean
}

type responseReportSuscription {
    message:String
    content:[reportSub]
    technicianData:[reportTech]
}

type reportSub {
    name_subs:String
    state_sub:String
    count_sub:String
}

type reportTech {
    name_sub:String
    type_report:[report]
}

type report {
    fullName_technician:String
    state_TechSub:String
    startSub:String
    endSub:String
}
