extend type Query {
    reportSuscription(Input:requestReportSuscription):responseReportSuscription @field(resolver: "ReportQuery@reportSuscription")
}

input requestReportSuscription {
    startDate:String
    endDate:String
    type:String
    state:String
    status:Boolean
}

type responseReportSuscription {
    message:String
    content:[reportSub]
    technicianData:[reportTech]
}

type reportSub {
    name_subs:String
    state_sub:String
    count_sub:String
}

type reportTech {
    name_sub:String
    type_report:[report]
}

type report {
    fullName_technician:String
    state_TechSub:String
    startSub:String
    endSub:String
}
