extend type Mutation {
    createPublicity(requestPublicity:JSON,logo:Upload):responsePublicit @field (resolver: "PublicityMutations@create")
    updatePublicity(id:ID!,requestPublicity:JSON,logo:Upload):responsePublicit @field (resolver: "PublicityMutations@update")
    deletePublicity(requestPublicity:JSON):responsePublicit @field (resolver: "PublicityMutations@delete")
    sendPublicity(id_p:String,id_a:String):publicityResp @field (resolver: "PublicityMutations@publicitySendAll")
}

type responsePublicit {
    message:String
    publicity: Publicity
}

type publicityResp {
    message:String
    state:Boolean
}
#import publicity.graphql
