extend type Query{
    getAgendaInternal(requestAgenda:JSON!):responseDetaiAgendaInternal @field(resolver: "AgendaQuery@listAgendaInternalClient" )
    getAgendaExternal(requestAgenda:JSON!):responseDetaiAgendaExternal @field(resolver: "AgendaQuery@listAgendaExternalClient" )

}

type responseDetaiAgendaInternal {
    message:String!
    agenda:[contentInternal]
}

type responseDetaiAgendaExternal {
    message:String!
    agenda:[contentExternal]
}

type contentInternal {
    agenda:Service
    technician:technician
    client:InternalClient
}

type contentExternal {
    agenda:Service
    technician:technician
    client:ExternalClient
}


#import detailAgendaTechnical.graphql
