extend type Mutation {
    createClientExternal(clientRequest:JSON!): ClientsResponse @field(resolver: "ClienteExternoMutations@create")
    updateClientExternal(clientRequest:JSON!): clientExternalResponse @field(resolver: "ClienteExternoMutations@update")
    deleteClientExternal(id_client: ID! , id_technician: ID!): Response @field(resolver: "ClienteExternoMutations@delete")
    #reactiveClientExternal(clientRequest:JSON): clientExternalResponse @field(resolver: "ClienteExternoMutations@reactivate")
}

type ClientsResponse {
  message: String
  customer_external: ExternalClient
  technical: Technician
}

type Response {
  message: String
}

type clientExternalResponse {
    message:String
    technical: Technician
    customerExternal: ExternalCustomer
}

type ExternalCustomer {
    full_name:String
    phone_number:String

}
#import ExternalClient.graphql
