extend type Mutation {
    createClientExternal(clientRequest:JSON!): ClientsResponse @field(resolver: "ClienteExternoMutations@create")
    updateClientExternal(clientRequest:JSON!): clientExternalResponse @field(resolver: "ClienteExternoMutations@update")
    deleteClientExternal(id_client: ID! , id_technician: ID!): Response @field(resolver: "ClienteExternoMutations@delete")
    #reactiveClientExternal(clientRequest:JSON): clientExternalResponse @field(resolver: "ClienteExternoMutations@reactivate")
}

type ClientsResponse {
  message: String
  customer_external: ExternalCustomer
  technical: Technician
}

type Response {
  message: String
}

type clientExternalResponse {
    message:String
    technical: Technician
    customer_external: ExternalCustomer
}

type ExternalCustomer {
    id:String
    fullName:String
    phoneNumber:String
    status:String
}
#import ExternalClient.graphql
