extend type Query {
    getAllSkills: [Skill] @all (model: "App\\Models\\Habilidad")
    getSkillById(id: ID! @whereKey): Skill @find (model: "App\\Models\\Habilidad")
    searchSkillTechnician(requestSkillTechnician:JSON):responseTechnician @field (resolver: "SkillQuery@searchSkillTechnician")

    filterSkillTechnician(requestSkillTechnician:JSON):responseTechnician_ @field (resolver: "SkillQuery@searchFilterSkillTechnician")
}

type responseTechnician {
    message:String
    technicians:[Technician]
}

type responseTechnician_ {
    message:String
    status:Int
    technicians:[technicians_]
}

type technicians_ {
    id:ID
    firstName:String
    lastName:String
    phoneNumber:String
    photo:String
    avg_rating:String
    skill:[skillS_]
}

type skillS_ {
    id_skills:String
    name:String
    experience:String
    icons:String
}
#import skill.graphql
