extend type Mutation {
  registerRequest(requestRequest:JSON!):requestResponse @field(resolver:"SolicitudesMutations@create")
  updateRequest(requestRequest:JSON!):requestResponseService @field(resolver:"SolicitudesMutations@modifyState")
}

type requestResponse {
    message:String!
    requests:Request
    client:InternalClient
    technician:Technician

}

type requestResponseService{
    message:String
    requests:Request
    client:InternalClient
    technician:Technician
    messageService:String
    service:Service
}

#import request.graphql
