extend type Query {
    requestTechnicalAll(id:ID!):responseTechnicalId @field (resolver: "RequestQuery@requestsTechnicalId")
    requestClientAll(id:ID!):responseClientId @field (resolver: "RequestQuery@requestsClientId")
    getListStatusRequest(requestRequest:JSON):responseTechnicalId @field (resolver: "RequestQuery@listStatusPendingComplet")
    getAgendaRequest(parameterSearch:JSON):responseAgendaRequest @field(resolver: "RequestQuery@agenda_requests")
    countRequest:responseCountReq @field(resolver: "RequestQuery@getRequestData")
}

type responseCountReq {
    message:String
    requestAll:String
    conteo:countReq
}

type countReq {
    requestPending:String
    requestAccept:String
    requestCancel:String
    requestComple:String
    requestAnulad:String
    requestTermin:String
}

type responseAgendaRequest{
    message:String
    status:Int
    request:[requestagenda]
}

type requestagenda {
    full_name:String
    phoneNumber:String
    id_services:String
    title:String
    description:String
    activity_name:String
    state_services:String
    datetime:String
}

type responseTechnicalId {
    message:String
    request:[_requesttechnician]
    technical:Technician
}

type _requesttechnician {
    request:Request
    client:_client
}


type responseClientId {
    message:String
    request:[_requestclient]
    client: InternalClient
}

type _requestclient {
    request:Request
    technician:_client
}
type _client {
    fullName:String
    phoneNumber:String
    ci:String
}

#import request.graphql
