extend type Query {
    requestTechnicalAll(id:ID!):responseTechnicalId @field (resolver: "RequestQuery@requestsTechnicalId")
    requestClientAll(id:ID!):responseClientId @field (resolver: "RequestQuery@requestsClientId")
    getListStatusRequest(requestRequest:JSON):responseTechnicalId @field (resolver: "RequestQuery@listStatusPendingComplet")
}

type responseTechnicalId {
    message:String
    request:[Request]
    technical:Technician
}

type responseClientId {
    message:String
    request:[Request]
    client: InternalClient
}

#import request.graphql
