extend type Mutation {
    createTechnician(technicianRequest: JSON!, frontIdCard: Upload, backIdCard: Upload ): TechnicianResponse @field(resolver:"TecnicoMutations@create")
    updateTechnician(id: ID!, technicianRequest: JSON! , photo: Upload): TechnicianResponse @field(resolver:"TecnicoMutations@update")
    deleteTecnico(id:ID! @whereKey): Response @field(resolver:"TecnicoMutations@delete")
}

type Response {
  message: String
}

type TechnicianResponse {
  user: User
  technician: Technician
  skill: TechnicianSkill
  message: String
  upcomingmessage: String
}
#import technician.graphql
