type Technician @model(class: "App\\Models\\Tecnico"){
  id: ID
  firstName: String @trim
  lastName: String @trim
  frontIdCard: String
  backIdCard: String
  email: String @trim
  phoneNumber: String
  password: String! @trim
  photo: String
  userId: String! @trim
  average_rating:String
  id_city: String! @rename (attribute: "cityId")

  city: City! @belongsTo
  user: User! @belongsTo

  technicianSkills: [TechnicianSkill!]! @hasMany
  associantions: [AssociationTechnClient!] @belongsTo

  ratings: [Rating] @hasMany
}

