extend type Query {
    getRolPermissions(name:String):responsePermissios @field (resolver: "RolQuery@getPermisse")
    getRolAdmin:responseRole @field(resolver: "RolQuery@getRol")
    getPermission(id_users:String):permissionResponse @field(resolver: "RolQuery@getUserPermissionId")
}

type permissionResponse {
    message:String
    status:Int
    permissions:[Permission]
}

type responsePermissios {
    message:String
    permissions:[Permission]
}

type responseRole {
    message:String
    rol:[Role]
}
#import role.graphql
