extend type Mutation {
    createServiceInternal(requestService:JSON!):responseServiceClient @field(resolver: "ServicioMutations@createInternal")
    createServiceExternal(requestService:JSON!):responseService @field(resolver: "ServicioMutations@createExternal")

    completServiceInternal(requestService:JSON):responseServiceClient @field(resolver: "ServicioMutations@finishServiceClientInternal")
    completServiceExternal(requestService:JSON):responseService @field(resolver: "ServicioMutations@finishServiceClientExternal")
    completServiceTechnician(requestService:JSON):responseServiceClient @field(resolver: "ServicioMutations@finishServiceTechnician")
    deleteService(requestService:JSON!):responseServiceDelete @field(resolver: "ServicioMutations@delete")
    updateService(id_service:ID , requestService:JSON!):responseServiceDelete @field(resolver: "ServicioMutations@updateService")
    verificationServices(requestService:JSON):verificationServ @field(resolver: "ServicioMutations@verificationsServicio")
}

type verificationServ {
    message:String
    status:Boolean
    services:[serv_ces]
}

type serv_ces{
    id_technician:String
    fullName_technician:String
    photo_technician:String
    id_client:String
    fullName_client:String
    photo_client:String
    id_service:String
    title_service:String
    description_service:String
}

type responseService {
    message:String
    service:Service
    customer_external:externalclient
    technician:Technician
}
type externalclient{
    id:String
    fullName:String
    phoneNumber:String
}
type responseServiceClient {
    message:String
    messageN:String
    service:Service
    customer_internal:InternalClient
    technician:Technician
}

type responseServiceDelete {
    message:String
    service:Service
}
#import service.graphql
