extend type Mutation {
    createService(requestService:JSON!):responseService @field(resolver:"ServicioMutations@create")
    updateService(requestService:JSON!):responseServiceClient @field(resolver:"ServicioMutations@update")
    deleteService(requestService:JSON!):responseServiceDelete @field(resolver:"ServicioMutations@delete")
}

type responseService {
    message:String
    service:Service
    customer_external:ExternalClient
}

type responseServiceClient {
    message:String
    messageN:String
    cita:Citation
    service:Service
    customer_external:ExternalClient
    customer_internal:InternalClient
}

type responseServiceDelete {
    message:String
    service:Service
}
#import service.graphql
