extend type Query {
    getListClientExternalAll(id:ID!):responseClientExternal @field (resolver: "ServiceQuery@getExternalClient")
    getListClientExternalEarring(id:ID!):responseClientExternal @field (resolver: "ServiceQuery@getExternalClientEarring")
    getListClientExternalOver(id:ID!):responseClientExternal @field (resolver: "ServiceQuery@getExternalClientOver")
    getListClientExternalActivity(requestService:JSON):responseClientExternal @field (resolver: "ServiceQuery@getInternalClientActivity")
    getListClientInternalAll(id:ID!):responseClientInternal @field (resolver: "ServiceQuery@getInternalClient")
    getHistoryInternalClient(requestService:JSON):historyServiceInternal @field (resolver: "ServiceQuery@technicianHistoryClientInternal")
    getHistoryExternalClient(requestService:JSON):historyServiceExternal @field (resolver: "ServiceQuery@technicianHistoryClientExternal")
    collectClientServices(requestService:JSON):responseServices @field (resolver: "ServiceQuery@listsServiceClient")
    listRequestsAccept(id_client:String):responseListService @field(resolver: "ServiceQuery@getListRequestNow")
    getServiceId(id_service:String):responseServiceId @field (resolver: "ServiceQuery@getServiceById")
    getCountService:responseServ @field(resolver: "ServiceQuery@getCountServicesStateActivity")
}

type responseServ{
    message:String
    contAll:String
    contState:countState
    contActivity:countActivity
}

type countState{
    servicePending:String
    serviceFinish:String
    serviceComplt:String
}

type countActivity{
    serviceMant:String
    serviceRepa:String
    serviceInst:String
    serviceInsp:String
}

type responseServiceId{
    message:String
    cont_services:conService
    cont_technician:conTechnician
}

type conService {
    titleService:String
    serviceDescription:String
    visitDate:String
    latitude:String
    longitude:String
    serviceLocation:String
    descripcionActivity:String
    state_service:String
}

type conTechnician {
    full_name:String
    photo:String
    phoneNumber:String
    average_rating:String
}

type responseListService {
    message:String
    requests:[listRequest]
}

type listRequest {
    id_requests:String
    id_services:String
    photo:String
    full_name:String
    titleRequests:String
    descripcionActivity:String
    visitDate:String
    observations:String
    status:String
}

type responseClientExternal {
    message:String
    service:[services]
    technician:Technician
}

type responseClientInternal {
    message:String
    service:[services_]
    technician:Technician
}

type responseServices {
    message:String
    counter:String
    services:[serv]
}

type serv {
    serviceContent:Service
    technician:Technician
}

type services {
    _service:Service
    customer_external:ExternalClient
}

type services_ {
    _service:Service
    customer_internal:InternalClient
}

type historyServiceInternal {
    message:String
    service:[Services_]
}

type historyServiceExternal {
    message:String
    service:[Service_]
}

type Services_ {
    service_id:String
    titleService:String
    serviceDescription:String
    serviceLocation:String
    technicalId:String
    clientId:String
    updatedDateTime:String
    service_origin:String
    finishDateTime_client:String
    finishDateTime_technician:String
    rating_id:String
    rating:String
    comments:String
    activityId:String
}

type Service_ {
    service_id:String
    titleService:String
    serviceDescription:String
    serviceLocation:String
    latitude:String
    longitude:String
    technicalId:String
    clientId:String
    activityId:String
    updatedDateTime:String
}
#import service.graphql
