type Service {
    id:ID
    id_state:ID @rename(attribute: "stateId")
    id_requests:ID @rename(attribute: "requestsId")
    id_technician:ID! @rename(attribute: "technicalId")
    id_client:ID @rename(attribute: "clientId")
    id_activity: ID! @rename(attribute: "activityId")
    typeClient:String!
    titleService: String @trim
    serviceDescription:String @trim
    serviceLocation:String @trim
    latitude:String
    longitude:String
    status:String
    createdDateTime:String
    updatedDateTime:String
    finishDateTime_client:String
    finishDateTime_technician:String

    
    request:[Request!]! @hasMany

    rating:Rating @hasOne
}
