type Service {
    id:ID!
    id_state:ID! @rename(attribute: "stateId")
    id_requests:ID @rename(attribute: "requestsId")
    id_technician:ID! @rename(attribute: "technicalId")
    id_client:ID! @rename(attribute: "clientId")
    typeClient:String!
    serviceDescription:String
    status:String
    programDate:String
    finishedDate:String
    requestsDate:String!

    state:StateType! @belongsTo
    request:[Request!]! @hasMany
    service: Citation! @belongsTo

    ratings:[Rating] @hasOne
}
