extend type Mutation {
    createUser(userRequest: JSON): User @field(resolver: "UserMutations@create")
    updateUser(id: ID!, userRequest: JSON!): User @field(resolver: "UserMutations@update")
    deleteUser(id:ID! @whereKey): Response @field(resolver: "UserMutations@delete")
    login(ci: String! ,password:String!):responseLogin @field(resolver: "UserMutations@login")
    loginClient(email: String! ,password:String! , expo_token:String):responseClientLogin @field(resolver: "UserMutations@loginClient")
    loginAdmin(email:String!,password:String!):responseAdminLogin2 @field(resolver: "UserMutations@loginAdmin")

    logout:Response @field(resolver: "UserMutations@logout")
    anullUserAdm(id_user:String):userResponseStat @field(resolver: "UserMutations@anullUser")
    upUserAdm(id_user:String):userResponseStat @field(resolver: "UserMutations@setUpUser")
}

type userResponseStat {
    message:String
    users:User
}

type Response {
  message: String
}

type responseLogin {
  user: User
  technician: Technician
  skills: [skills]
  message: String
}

type responseClientLogin {
    user: User
    city:citiess
    client: InternalClient
    message:String
    status:Int
    devices:devices
}

type devices {
    device_id:String
    expo_token:String
    user_id:String
    name_device:String
    type_device:String
}

type citiess {
    id_city:ID
    name:String
}

type responseAdminLogin2 {
    message:String
    user:User
    role:Role
    permissions:[Permission]
}
type skills {
    id_skill:ID!
    name:String
    experience:String
}
#import user.graphql

