#mutation.graphql

extend type Mutation {
    createUser(userRequest: JSON!): User @field(resolver:"UserMutations@create")
    updateUser(id: ID!, userRequest: JSON!): User @field(resolver:"UserMutations@update")
    deleteUser(id:ID! @whereKey): Response @field(resolver:"UserMutations@delete")
    login(ci: String! ,password:String!):responseLogin @field(resolver:"UserMutations@login")
    logout:Response @field(resolver:"UserMutations@logout")
}
union userRol = Technician | InternalClient

type Response {
  message: String
}

type responseLogin {
  user: User
  technician: Technician
  skills: [Skill]
  message: String
}
#import user.graphql

