extend type Query {
  getAllUsers: [User] @all
  getUserById(id: ID! @whereKey): User @find
  getUserRol: responseRolUser @field(resolver: "UserQuery@getUserRol")
  me:responseAdminLogin @field(resolver: "UserQuery@me")
  countParams:paramsCount @field(resolver: "UserQuery@countParams")
}

type paramsCount{
    technician:String
    client:String
    requests:String
    service:String
}

type responseAdminLogin {
    id:ID
    email:String
    role:Role
    permissions:[Permission]
}

type responseRolUser {
    message:String
    succes:String
    user:[Usser]
}

type Usser {
    id:String
    name:String
    email:String
    status:String
    roles:[Roleee]
    permissions:[Permission]
}

type Roleee {
    name:String
}
#import user.graphql
