extend type Mutation {
    sendNotifications( input:sendNotificationInput ): notificationsResponse @field(resolver: "NotificationMutations@send")
}

input sendNotificationInput {
    title: String
    body:String
    data:JSON
    type:notificationTypeEnum
    datetime_send:DateTime
    status:String
}

enum notificationTypeEnum {
    request     #solicitud
    service     #servicio
    accept      #aceptado
    reject      #rechazado
    promotion   #promocion
    publicity   #publicidad
    message     #mensaje
}

type notificationsResponse {
    message:String
    success:Boolean
    notification:Notification
}

type Notification {
    id:ID
    title:String
    body:String
    data:JSON
    type:String
    datetime_send: DateTime
    status: String
}

