extend type Mutation {
    sendNotifications( Input:sendNotificationInput ): notificationsResponse @field(resolver: "NotificationMutations@send")
}

input sendNotificationInput {
    data:JSON
    action_key:String
    type:notificationTypeEnum
    senderDevice:String
    send_at:String
    status:statusEnum
    sender_token:String
    receivers:[String]
}

enum notificationTypeEnum {
    solicitud       #solicitud
    servicio        #servicio
    aceptado        #aceptado
    rechazado       #rechazado
    promocion       #promocion
    publicidad      #publicidad
    mensaje         #mensaje
}

enum statusEnum {
    enviada
    pendiente
    fallida
    cancelada
}

type notificationsResponse {
    message:String
    success:Boolean
    notification:Notification
}

type Notification {
    id:ID
    title:String
    body:String
    data:JSON
    type:String
    datetime_send: DateTime
    status: String
}

