extend type Mutation {
    sendNotifications( input:sendNotificationInput ): notificationsResponse @field(resolver: "NotificationMutations@send")
}

input sendNotificationInput {
    title: String
    body:String
    data:JSON
    type:notificationTypeEnum
    datetime_send:String
    status:String
}

enum notificationTypeEnum {
    solicitud       #solicitud
    servicio        #servicio
    aceptado        #aceptado
    rechazado       #rechazado
    promocion       #promocion
    publicidad      #publicidad
    mensaje         #mensaje
}

type notificationsResponse {
    message:String
    success:Boolean
    notification:Notification
}

type Notification {
    id:ID
    title:String
    body:String
    data:JSON
    type:String
    datetime_send: DateTime
    status: String
}

