extend type Query {
    getNotificationsTechnician(Input:requestNotification):responseNotificationTech @field(resolver: "NotificationsQuery@getNotificationsTech" )
    getNotificationsClient(Input:requestNotificationClient):responseNotificationClient @field(resolver: "NotificationsQuery@getNotificationsClient" )
}

input requestNotificationClient {
    userClient:String
}

type responseNotificationClient {
    message:String
    client:InternalClient
    notification:[getnotify]
}

input requestNotification {
    userTech:String
}

type responseNotificationTech {
    message:String
    technician:Technician
    notification:[getnotify]
    notifications:[getsnotify]
}

type getnotify {
    actions_key:String
    sent_at:String
    title:String
    description:String
    data:JSON
}

type getsnotify {
    expo_response:String
    created_at:String
    notification_id:String
    actions_key:String
    sender_id:String
    title:String
    data:JSON
}

