extend type Query {
    getNotificationsTechnician(Input:requestNotification):responseNotificationTech @field(resolver: "NotificationsQuery@getNotificationsTech" )
    getNotificationsClient(Input:requestNotificationClient):responseNotificationClient @field(resolver: "NotificationsQuery@getNotificationsClient" )
}

input requestNotificationClient {
    userClient:String
}

type responseNotificationClient {
    message:String
    client:InternalClient
    notification:[getnotify]
}

input requestNotification {
    userTech:String
}

type responseNotificationTech {
    message:String
    status:String
    notifications:[getnotify]
}

type getnotify {
    id:String
    title:String
    date:String
    body:String
    data:JSON
    type: String
}

