extend type Query {
    getNotificationsTechnician(Input:requestNotification):response @field(resolver: "TypeNotificationQuery@getNotificationsTech" )
    getNotificationsClient(requestNotification:JSON):response @field(resolver: "TypeNotificationQuery@getNotificationsClient" )
}

input requestNotification {
    userTech:String
}

type responseNotificationTech {
    message:String
    technician:Technician
    notification:[getnotify]
}

type getnotify {
    sent_at:String
    title:String
    description:String
    data:String
    code_notifications:String
    full_name:String
    phoneNumber:String
}

