extend type Query {
    #geservicetGroupName:GroupSkill @all (model: "App\\Models\\Skills_group")
    getServiceCategory:responseGroups @field(resolver: "GroupSkillQuery@allGroupSkill")
    getServiceCategory_:responseGroup_ @field(resolver: "GroupSkillQuery@allGroupSkill_")
}

type responseGroups{
    message:String
    subCategory:[Group]
}

type responseGroup_{
    message:String
    subCategory:[responseSkills]
}

type responseSkills {
    id:ID
    nameCategory:String
    photo:String
    skill: [Skill]
}
#import GroupSkill.graphql
