extend type Mutation {
    registerClient(clientRequest:JSON! photo:Upload): ClientResponse @field(resolver: "ClienteInternoMutations@create")
    updateClient(id: ID,clientRequest:JSON!): ClientResponse @field(resolver: "ClienteInternoMutations@update")
    deleteClient(id: ID! @whereKey): Response @field(resolver: "ClienteInternoMutations@delete")
    updatePhoto(id_client:ID, photo:Upload):ClientResponse @field(resolver: "ClienteInternoMutations@updatePhoto")
    resetPasswordClient(id_client:ID,new_password:String):responsePassClient @field(resolver: "ClienteInternoMutations@resetPasswordclientAtSupport")
}


type responsePassClient{
    message:String
    result:Int
}

type Response {
  message: String
}

type ClientResponse {
  message: String
  client: InternalClient
  city:cities
  user: User
  status:Int
}

type cities {
    id_city:ID
    name:String
}
#import InternalClient.graphql
