extend type Mutation {
    createClient(clientRequest:JSON! photo:Upload): ClientResponse @field(resolver:"ClienteInternoMutations@create")
    updateClient(id: ID,clientRequest:JSON! photo:Upload ): ClientResponse @field(resolver:"ClienteInternoMutations@update")
    deleteClient(id: ID! @whereKey): Response @field(resolver:"ClienteInternoMutations@delete")
}

type Response {
  message: String
}

type ClientResponse {
  message: String
  client: InternalClient
  user: User
}

#import InternalClient.graphql
