extend type Query {
    clientAllow:[InternalClient] @all (model: "App\\Models\\Cliente_Interno")
    searchClientInternalByName(requestClient:JSON):responseClientInternalSearch @field(resolver: "ClientQuery@searchInternalByName")
    clientInternalById(id:ID! @whereKey):InternalClient @find(model: "App\\Models\\Cliente_Interno")
    historyClientInternal(clientRequest:JSON):responseHistorial @field( resolver: "ClientQuery@list_requests_services")
    listRequestAccept(id_client:String):responseGetRequest @field( resolver: "App\\GraphQL\\Queries\\ClientQuery@clientInternalAcept")
}

type responseGetRequest{
    message:String
    contentClient:[clientContent]
}

type clientContent{
    id_request:String
    date:String
    title:String
    description:String
    state_name:String
    full_name:String
}

type responseClientInternalSearch{
    message: String
    request:Request
    client_i: [InternalClient]
}

type responseHistorial{
    message: String
    client:InternalClient
    historial:[historialDetail]
}

type historialDetail{
    type:String
    technician:Technician
    detail:historyItemDetail
}

type historyItemDetail{
    title:String
    description:String
    dateCreate:String
    dateFinish:String
}

#import InternalClient.graphql
